name: Check1

on:
    pull_request:
        paths:
            - check1.txt
    workflow_dispatch:

jobs:
    check:
        name: Check1
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: check
              run: if [ $(cat check1.txt | grep -c ok) -eq 1 ]; then exit 0; else exit 1; fi
