name: Check2

on:
    pull_request:
        paths:
            - check2.txt
    workflow_dispatch:

jobs:
    check:
        name: Check2
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: check
              run: if [ $(cat check2.txt | grep -c ok) -eq 1 ]; then exit 0; else exit 1; fi
